# Generated by Django 5.1.7 on 2026-07-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=120)),
                ('purpose', models.TextField()),
                ('destination', models.CharField(max_length=200)),
                ('visit_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor Pass',
                'verbose_name_plural': 'Visitor Passes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='visitors_vi_status_663263_idx'), models.Index(fields=['email'], name='visitors_vi_email_956c68_idx'), models.Index(fields=['mobile'], name='visitors_vi_mobile_70fb36_idx')],
            },
        ),
    ]
