# Generated by Django 5.1.7 on 2026-07-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('administrative', 'Administrative'), ('hostel', 'Hostel'), ('library', 'Library'), ('laboratory', 'Laboratory'), ('cafeteria', 'Cafeteria'), ('sports', 'Sports'), ('parking', 'Parking'), ('gate', 'Gate / Entrance'), ('other', 'Other')], db_index=True, default='academic', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('floor_count', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'name'], name='buildings_b_categor_3b86fc_idx'), models.Index(fields=['is_active'], name='buildings_b_is_acti_3c43aa_idx')],
            },
        ),
    ]
